services:
  nginx:
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - /home/ntaleb/data/wordpress:/app
      - /home/ntaleb/data/adminer:/adminer
    networks:
      - lemp

  wordpress:
    build: requirements/wordpress
    restart: always
    volumes:
      - /home/ntaleb/data/wordpress:/app
    networks:
      - lemp

  mariadb:
    build: requirements/mariadb
    restart: always
    volumes:
      - /home/ntaleb/data/mariadb:/var/lib/mysql
    networks:
      - lemp

  ftp:
    build: requirements/ftp
    restart: always
    volumes:
      - /home/ntaleb/data/wordpress:/app
    ports:
      - "21:21"
    networks:
      - lemp


  redis:
    build: requirements/redis
    restart: always
    networks:
      - lemp

  adminer:
    build: requirements/adminer
    restart: always
    volumes:
      - /home/ntaleb/data/adminer:/adminer
    networks:
      - lemp

networks:
  lemp:
